### PR TITLE
feat: Add redis streams length e2e test images (#4277)

### PR DESCRIPTION
**Pull request by jkbmdk**
Images added for testing issue https://github.com/kedacore/keda/issues/4277

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] A PR is opened to update the documentation on [our docs repo](https://github.com/kedacore/keda-docs)

Fixes #

### CODE REVIEW

**Comment by JorTurFer** [comment]
Hi,
What has changed from already existing images? The only change I can see is that these images don't consume the messages (or at least, I can't see how)

**Comment by jkbmdk** [comment]
Hey, current images (for cluster and sentinel) reads messages and acks on them, but do not removes them from the stream, it works as an append only stream. Provided images pops out readen messages, so the stream length decreases

**Review by zroubalik — COMMENTED** [review]
Thanks!
I am curious wouldn't it make a sense to modify existing images and sources? ie. add some parameter to enable/disable this feature?
This might be easier to maintain for us.

**Comment by jkbmdk** [comment]
I think it's possible to extend redis _cluster_ and _sentinel_ images, but _standalone_ is outside of the repository

**Comment by JorTurFer** [comment]
I think that if this is something we can parametrize, we could parametrize it and also adding the code for standalone redis. I mean, you have already added the code with the new feature, you could just replace the already existing external image using your code with the flag

**Comment by jkbmdk** [comment]
I've made one image handling all redis-streams test cases, "one to rule them all"

**Review by JorTurFer — APPROVED** [review]
LGTM!
Thanks for the improvement

**Pull request merged**
