### PR TITLE
Adding image for external scaler e2e test.

### PR DESCRIPTION
**Pull request by v-shenoy**
Signed-off-by: Vighnesh Shenoy <vshenoy@microsoft.com>

Relates to https://github.com/kedacore/keda/issues/2640

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO)
- [x] A PR is opened to update the documentation on [our docs repo](https://github.com/kedacore/keda-docs)

Fixes #

### CODE REVIEW

**Comment by v-shenoy** [comment]
@zroubalik @JorTurFer I will be adding e2e tests for external scaler along with a fix for https://github.com/kedacore/keda/issues/2640. Need this image to be uploaded to GHCR so that I can use it in the test.

**Review by zroubalik — APPROVED** [review]
LGTM!

**Comment by v-shenoy** [comment]
Thanks for approving, @zroubalik. I think the image has been pushed, but the default visibility on `ghcr` is private, it seems?

**Comment by zroubalik** [comment]
@v-shenoy you are right, sorry I forgot about this, fixed!

**Pull request merged**
